<?php


declare(strict_types=1);
namespace validators\bank;

use validators\Validator;

Class Bank extends Validator {
    private $agencia;
    private $numeroConta;

    public function __construct(string $agencia, string $numeroConta) {
        $this->numeroConta=$numeroConta;
        $this->agencia=$agencia;
        $this->numeroConta=str_replace('P', '0', $this->numeroConta);

        //$value = (int)($this->agencia . $this->numeroConta);
        //parent::__construct($value);

    }

    public function toFormatted():string {
        // TODO: Implement toFormatted() method.
        return '';
    }

    public function validateAg():bool {
        $agencia = str_split($this->agencia);
        $valores = array (5, 4, 3, 2);
        $soma = 0;
        $cont = 0;
        foreach ($valores as $y) {
            $soma = $soma + ($y * (int)$agencia[$cont]);
            $cont++;
        }
        $mod = 11 - ($soma % 11);
        if ($mod == 10 or $mod == 11) {
            if ($this->numeroConta == 0) {

            }
        }
        return true;
    }

    public function validate():bool {
        $this->numeroConta= (string)str_replace('-', '', $this->numeroConta);
        $this->numeroConta=str_split($this->numeroConta);
        $soma = 0;
        $contador = 0;

        $pesos = array(2, 7, 6, 5, 4, 3, 2);
        foreach ($pesos as $value) {
            $soma = $soma + ($value * $this->numeroConta[$contador]);
            $contador++;
        }
        $mod = $soma % 11;
        if ($mod == 0 || $mod == 1) {
            if ($this->numeroConta[$contador] == 0) {
                return true;
            }
        }
        else {
            $mod = 11 - $mod;
            if ($mod == $this->numeroConta[$contador]) {
                return true;
            }
        }
        return false;
    }

    /**
     * Replace X with zero if exists in $valye
     * @return int
     */
    public function toInteger():int {
        
        return 1; // TODO: Change the autogenerated stub
    }

}